image: continuumio/miniconda3

stages:
  - pre-commit
  - prepare
  - build
  - test
  - coverage

before_script:
  - conda init bash
  - source ~/.bashrc
  - conda info --envs
  - conda env create -f environment.yml || conda env update -f environment.yml
  - conda activate madupiteenv

pre-commit:
  stage: pre-commit
  script:
    - conda install -c conda-forge pre-commit
    - pre-commit run --all-files

create_environment:
  stage: prepare
  script:
    - conda env create -f environment.yml || conda env update -f environment.yml
    - echo "Environment created or updated"

build:
  stage: build
  script:
    - echo "Building the project"
    - cmake -S . -B build
    - make -C build
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - echo "Running tests"
    # Your test commands here
    - cd build
    - ./ci-test
    # - mpirun -n 2 ./ci-test
    - echo "Finished with code $?"

coverage:
  stage: coverage
  script:
    - cmake -DCMAKE_BUILD_TYPE=Coverage -S . -B build
    - make -C build
    - cd build
    - ./ci-test
    - gcovr -r .. --xml-pretty -o coverage.xml # Generates a Cobertura-compatible XML report
    - gcovr -r .. --html -o coverage.html --html-details # Generates a detailed HTML report (optional)
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}"
    expire_in: 2 days
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - coverage.xml
      - coverage.html

