image: continuumio/miniconda3

stages:
  - prepare
  - build
  - test

variables:
  CONDA_ENV_PATH: "${CI_PROJECT_DIR}/madupiteenv"

default:
  cache: &global_cache
    key:
      files:
        - environment.yml
    paths:
      - madupiteenv/
    policy: pull

before_script:
  - conda init bash
  - source ~/.bashrc
  - conda env list
  - |
    if [ -f environment.yml ]; then
      if [ -d ${CONDA_ENV_PATH} ]; then
        echo "Reusing Conda environment ${CONDA_ENV_PATH}"
        conda env update --prefix ${CONDA_ENV_PATH} -f environment.yml
      else
        echo "Creating new Conda environment ${CONDA_ENV_PATH}"
        conda env create --prefix ${CONDA_ENV_PATH} -f environment.yml
      fi
    else
      echo "environment.yml not found"
      exit 1
    fi
  - conda activate ${CONDA_ENV_PATH}
  - conda env list

init:
  stage: prepare
  script:
    - pre-commit run --all-files
  cache:
    <<: *global_cache
    policy: pull-push

build:
  stage: build
  script:
    - echo "Building the project"
    - cmake -S . -B build
    - make -C build
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - echo "Running tests"
    # Your test commands here
    - cd build
    - ./ci-test
    - mpirun -n 2 ./ci-test
    - echo "Finished with code $?"
