image: continuumio/miniconda3

stages:
  - prepare
  - build
  - test

variables:
  CONDA_ENV_PATH: "${CI_PROJECT_DIR}/madupiteenv"

default:
  cache: &global_cache
    key:
      files:
        - environment.yml
    paths:
      - madupiteenv/
    policy: pull

workflow:
  rules:
    # only run within merge requests...
    - if: $CI_MERGE_REQUEST_ID
    # or for any commit in the default branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

before_script:
  - eval "$(conda shell.bash hook)"
  - conda env list
  - |
    if [ -f environment.yml ]; then
      if [ -d ${CONDA_ENV_PATH} ]; then
        echo "Reusing Conda environment ${CONDA_ENV_PATH}"
        conda env update --prefix ${CONDA_ENV_PATH} -f environment.yml
      else
        echo "Creating new Conda environment ${CONDA_ENV_PATH}"
        conda env create --prefix ${CONDA_ENV_PATH} -f environment.yml
      fi
    else
      echo "environment.yml not found"
      exit 1
    fi
  - conda activate --no-stack ${CONDA_ENV_PATH}
  - conda env list
  - export PETSC_DIR=${CONDA_PREFIX}
  - export PETSC_ARCH=
  - echo PETSC_DIR=$PETSC_DIR
  - echo PETSC_ARCH=$PETSC_ARCH

init:
  stage: prepare
  script:
    - pre-commit run --all-files
  cache:
    <<: *global_cache
    policy: pull-push

build:
  stage: build
  script:
    - pip install .
    - mkdir -p build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - cd build
    - make test
    - ctest --output-on-failure
  dependencies:
    - build
