[build-system]
requires = ["setuptools", "wheel", "scikit-build", "cmake", "nanobind"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
test-requires = ["pytest"]
test-command = "pytest {project}/tests"
