include ../../makefile_variables
RESULT := $(MADUPITE_LIB)
BUILD_DIR := $(BUILD_DIR_ABS)
# clang-format has troubles with json.h currently
# FORMATTED_STUFF += $(wildcard $(PROJECT_ROOT)/include/*.h)
FORMATTED_STUFF += $(PROJECT_ROOT)/include/MDP.h
FORMATTED_STUFF += $(PROJECT_ROOT)/include/JsonWriter.h
include ../../makefile_rules
