name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: madupiteenv
        environment-file: environment.yml
        auto-activate-base: false

    - name: Run pre-commit on all files
      run: conda run -n madupiteenv pre-commit run --all-files

    - name: Install the library
      run: conda run -n madupiteenv pip install .

    - name: Build and test with CMake
      run: |
        conda run -n madupiteenv bash -c "mkdir -p build && cd build && cmake .. -DBUILD_TESTS=ON && make && ctest --output-on-failure"

    - name: Run MPI executables
      run: |
        conda run -n madupiteenv bash -c "cd build && mpirun -np 4 ./ci_test"

    - name: Deploy documentation to GitHub Pages
      if: github.ref == 'refs/heads/main'
      run: |
        git config --global user.name 'Documentation Deploy GitHub Action'
        git config --global user.email '-'
        conda run -n madupiteenv bash -c "pip install pydata-sphinx-theme && cd docs && make html"
        cd docs/_build/html
        git init
        git remote add origin https://github.com/${{ github.repository }}.git
        git checkout -b gh-pages
        git add .
        git commit -m "Deploy docs to GitHub Pages"
        git push --force origin gh-pages
